### ISSUE TITLE
uninitialized constant ActionController::TestRequest

### ISSUE THREAD

**Issue by rb2k** [adamsalter/sitemap_generator#1]
# rake sitemap:refresh --trace

(in /var/www/marc-seeger.de)
*\* Invoke sitemap:refresh (first_time)
*\* Invoke sitemap:create (first_time)
*\* Invoke environment (first_time)
*\* Execute environment
*\* Invoke sitemap:clean (first_time)
*\* Execute sitemap:clean
*\* Execute sitemap:create
rake aborted!
uninitialized constant ActionController::TestRequest
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:440:in `load_missing_constant'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/activesupport-2.3.2/lib/active_support/dependencies.rb:80:in`const_missing'
/var/www/marc-seeger.de/vendor/plugins/sitemap_generator-plugin/lib/sitemap_generator/helper.rb:5:in `load_sitemap_rb'
/var/www/marc-seeger.de/vendor/plugins/sitemap_generator-plugin/tasks/sitemap_generator_tasks.rake:29
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in`call'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:636:in `execute'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in`each'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:631:in `execute'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:597:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:607:in `invoke_prerequisites'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in`each'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:604:in `invoke_prerequisites'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:596:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/1.8/monitor.rb:242:in `synchronize'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:590:in`invoke_with_call_chain'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:583:in `invoke'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2051:in`invoke_task'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in`each'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2029:in `top_level'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in`standard_exception_handling'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2023:in `top_level'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2001:in`run'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:2068:in `standard_exception_handling'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake.rb:1998:in`run'
/opt/ruby-enterprise-1.8.6-20090421/lib/ruby/gems/1.8/gems/rake-0.8.7/bin/rake:31
/opt/ruby-enterprise-1.8.6-20090421/bin/rake:19:in `load'
/opt/ruby-enterprise-1.8.6-20090421/bin/rake:19

And just FYI:
**\* LOCAL GEMS ***

actionmailer (2.3.2)
actionpack (2.3.2)
activerecord (2.3.2)
activeresource (2.3.2)
activesupport (2.3.2)
addressable (2.1.0, 2.0.2)
builder (2.1.2)
chronic (0.2.3)
coderay (0.8.312)
cucumber (0.3.11)
data_objects (0.9.12, 0.9.11)
date-performance (0.4.7, 0.4.6)
diff-lcs (1.1.2)
dm-aggregates (0.9.11)
dm-core (0.9.11)
do_mysql (0.9.12, 0.9.11)
extlib (0.9.12, 0.9.11)
fastthread (1.0.7)
gchartrb (0.8)
hoe (2.3.2, 2.3.1, 2.1.0, 2.0.0)
lesstile (0.3)
mislav-will_paginate (2.3.11)
mysql (2.7)
nokogiri (1.3.2, 1.3.1, 1.2.3)
passenger (2.2.4, 2.2.3, 2.2.2, 2.2.1)
polyglot (0.2.6, 0.2.5)
postgres (0.7.9.2008.01.28)
rack (1.0.0, 0.9.1)
rack-cache (0.5)
rails (2.3.2)
rake (0.8.7, 0.8.4)
RedCloth (4.2.2, 4.2.1, 4.2.0, 4.1.9)
rspec (1.2.7, 1.2.6)
ruby-openid (2.1.7, 2.1.6)
rubyforge (1.0.3)
sequel (3.2.0, 3.1.0)
sinatra (0.9.2, 0.9.1.1)
sqlite3-ruby (1.2.4)
term-ansicolor (1.0.3)
treetop (1.2.6, 1.2.5)

**Comment by adamsalter** [comment]
I've just tried a fix (I don't see this issue btw)
Try doing:
./script/plugin install git://github.com/adamsalter/sitemap_generator-plugin/tree/issue_1
Does that fix it?

**Comment by adamsalter** [comment]
issue resolved.

**Comment by batasrki** [comment]
Hey Adam,

I'm not sure if you pushed the resolution to the main branch, but I've encountered the same problem while installing the plugin just an hour ago.

**Comment by rb2k** [comment]
the solution is to modify the created config/sitemap.rb to your needs, there are some examples in there that have to be deleted/modified according to your app

**Comment by batasrki** [comment]
OK, so I've removed all of the example code. I've added my own. I've changed the default host to localhost in order to see if that affects it. In all cases, I still get the same response. Is there something I'm missing?

**Comment by adamsalter** [comment]
guys... I've pushed the fix to the master branch...
I don't really understand this problem... seems to work fine for most people (me included)...
But i've done the fix.
Just delete the plugin and reinstall... (it won't overwrite any changes to config/sitemap.rb)

**Comment by batasrki** [comment]
adam,

It seems to be working now. The rake task throws an error, but it's an error with my configuration that can be corrected.

Thanks for the quick response and patch.
