### ISSUE TITLE
gem

### ISSUE THREAD

**Issue by ghazel** [adamsalter/sitemap_generator#2]
Can we please have this in a gem instead of a plugin?

**Comment by adamsalter** [comment]
I don't really think it's necessary, the functionality is really only for rails (ie not all ruby projects) and rake tasks are not automatically added to a rails project for gems...
bonuses of having a gem: changes could be updated, but the project hasn't changed for a while now...

why do you want a gem?

**Comment by adamsalter** [comment]
Not really necessary. Plugin installation is easy.

**Comment by kjvarga** [comment]
This has been implemented.
