### ISSUE TITLE
tasks are polluting object with sitemap generator methods

### ISSUE THREAD

**Issue by richievos** [adamsalter/sitemap_generator#3]
The following lines live in sitemap:create:
    task :create => [:environment] do
      include SitemapGenerator::Helper
      include ActionView::Helpers::NumberHelper

When those lines run, they're running their include on Object, adding a bunch of junk to it. 

To prove this, add this to your Rakefile

```
at_exit { puts "I am #{self.class.name} and I have load_sitemap_rb defined on me? #{methods.include?('load_sitemap_rb')}" }
```

then run rake sitemap:create

I think the underlying issue is that there's quite a bit of code in the tasks file, that should maybe live somewhere else.

I'll take a crack at refactoring this and reference this issue.

**Comment by richievos** [comment]
I took a crack at it http://github.com/jerryvos/sitemap_generator/commit/69979bc78b593df6987fa53be86abbc053b1c860

**Comment by kjvarga** [comment]
Resolved.
