### ISSUE TITLE
Sitemap generator loads application controller when defining itself

### ISSUE THREAD

**Issue by richievos** [adamsalter/sitemap_generator#4]
This is giving me 2 issues:
1. My classes aren't reloading properly when sitemap gets loaded into my app. I think this has to do with my sitemap referencing some classes when generating urls, but it goes away whenever I comment out sitemap from my required gems.
2. My AppController references other classes. When I include sitemap it tries loading my app controller before all of those dependencies have been loaded, which ends up blowing up.

I think this can all be simplified by not touching application controller at all, and going directly at the underlying rails path utilities.

I think I have this working without ever touching the application controller, so I'll send a patch when I confirm.

**Comment by richievos** [comment]
I switched to using UrlWriter directly instead of App controller at http://github.com/jerryvos/sitemap_generator/commit/c31e88374aec08a575c1f17e2d13377d984c3c93

**Comment by kjvarga** [comment]
Resolved.
