### ISSUE TITLE
Sitemap_generator not compatible with Rails 3

### ISSUE THREAD

**Issue by nono** [adamsalter/sitemap_generator#5]
Hi,

sitemap_generator is not compatible with Rails 3. Do you have plans to update it?

The error:
    /home/nono/gem/gems/actionpack-3.0.0.beta/lib/action_controller/metal/url_for.rb:90: undefined method `class_attribute' for SitemapGenerator::Helper:Module (NoMethodError)

**Comment by kjvarga** [comment]
I have a Rails 3 compatibility patch that I will look into shortly, so yes, I am planning on getting that sorted.

**Comment by nono** [comment]
Cool. i'm impatient to test it ;-)

**Comment by kjvarga** [comment]
Good news! I've added Rails 3 support to version 0.2.5!  Check it out and let me know if you have any problems.

Cheers,
Karl

**Comment by nono** [comment]
Thanks. I've tried it on a project in development, and it seems to work fine :-)
