### ISSUE TITLE
Yahoo 403

### ISSUE THREAD

**Issue by ghazel** [adamsalter/sitemap_generator#7]
Sitemap stats: 436,086 links, 142m20s
Successful ping of Bing
Successful ping of Ask
Successful ping of Sitemap Writer
Successful ping of Google
Ping failed for Yahoo: #<OpenURI::HTTPError: 403 Forbidden>

**Comment by kjvarga** [comment]
For now, if you add this to your config/sitemap.rb file, it should stop trying to ping Yahoo:

SitemapGenerator::Sitemap.yahoo_app_id = false

**Comment by ghazel** [comment]
Ah, I upgraded and saw the helpful message about how to get an app id. I got one, and now pinging Yahoo works.

So, yay!

**Comment by kjvarga** [comment]
Good to hear :)
