### ISSUE TITLE
this is wrong: require 'sitemap_generator/tasks' rescue LoadError

### ISSUE THREAD

**Issue by ghazel** [adamsalter/sitemap_generator#8]
`require 'sitemap_generator/tasks' rescue LoadError` does not work.

Example: http://codepad.org/bEQIuIS6

You can do this: 
    begin
      require 'sitemap_generator/tasks'
    rescue LoadError
    end

Example: http://codepad.org/p27EDH1E

You could also do: `begin; require 'sitemap_generator/tasks'; rescue LoadError; end`

**Comment by kjvarga** [comment]
Thanks for the tip, I've updated the README
