### ISSUE TITLE
crc error of gz files, missing close for GZipWriter block

### ISSUE THREAD

**Issue by luislavena** [adamsalter/sitemap_generator#9]
I'm receiving incorrect crc errors from all the sitemaps files.

This happens from time to time, so is not consistent.

After digging into this, found this:

http://ruby-doc.org/core/classes/Zlib/GzipWriter.html
(read the note)

The missing @close@ to GZipWritter could be the problem. Seems the following places:

http://github.com/adamsalter/sitemap_generator/blob/master/tasks/sitemap_generator_tasks.rake#L49-51
http://github.com/adamsalter/sitemap_generator/blob/master/tasks/sitemap_generator_tasks.rake#L62-64

Need addition of `gz.close` prior leaving the block

Adding that locally solved the erratic crc errors

Thank you.

**Comment by kjvarga** [comment]
What version are you running?  In the latest, I am closing the Gzip stream.  In builder/sitemap_file.rb

```
    open(self.full_path, 'w') do |file|
      gz = Zlib::GzipWriter.new(file)
      gz.write @xml_wrapper_start
      gz.write @xml_content
      gz.write @xml_wrapper_end
      gz.close
    end
```

**Comment by luislavena** [comment]
Hmn, then you need to update the rake tasks?

http://github.com/adamsalter/sitemap_generator/blob/master/tasks/sitemap_generator_tasks.rake

Over there, the gz is not being closed? Those are the ones advertised to be used...

**Comment by kjvarga** [comment]
That's version 0.2.2 lol!  We are at 0.3.2 now!  Sitemap Generator has moved to kjvarga/sitemap_generator

**Comment by luislavena** [comment]
Hmn,

Better add that to the GitHub repo description then instead of the long first paragraph :-P

Also, to the README indicating that the repository is now deprecated :-D

Thank you!

**Comment by kjvarga** [comment]
Good idea.  Luckily I can push to his branch.  I've update the readme there to say that it's moved.

If you saw the gem on rubygems.org it has the new homepage and code repo on there.
